[package]
name = "chrono-tz"
version = "0.3.2"
authors = ["Djzin"]
build = "build.rs"
description = "TimeZone implementations for rust-chrono from the IANA database"
keywords = ["date", "time", "timezone", "zone", "calendar"]
repository = "https://github.com/djzin/chrono-tz"
documentation = "https://docs.rs/chrono-tz"
readme = "README.md"
license = "MIT/Apache-2.0"

[dependencies]
chrono = "0.3"
serde = { version = "^1.0", optional = true }
serde_derive = { version = "^1.0", optional = true }

[build-dependencies]
parse-zoneinfo = "0.1"

[features]
use_serde = ["serde", "serde_derive"]